MNT: rerender
conda-forge/atk-feedstock pull request #4
Opened 2018-07-15 20:28 UTC by conda-forge-linter

Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #3.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

Fixes #3

2018-07-15 20:28 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2018-07-15 20:29 UTC, jakirkham requested changes
Currently remove all CIs. So needs some work. Probably related to how things are pinned. Relaxing them should help.

2018-07-15 22:12 UTC, jakirkham requested changes
Seems to have dropped the macOS and Linux builds. Will need to investigate why and fix.

2018-09-28 13:41 UTC, pkgw commented
Superseded by #5.

2018-09-28 13:41 UTC, closed without merging